group=org.eclipse.edc
version=0.18.0

# information required for publishing artifacts:
edcScmConnection=scm:git:git@github.com:eclipse-edc/IdentityHub.git
edcScmUrl=https://github.com/eclipse-edc/IdentityHub.git

# construction-x-properties
con-x-edcVersion=0.18.0
jacksonVersion=2.21.3
junitVersion=6.1.1
junitPlatformVersion=6.1.1
mockitoVersion=5.23.0
assertjVersion=3.27.7
